// controllers/bookingController.js
const Booking = require('../models/bookingModel');
// Optional: Import Settings and Material models for advanced validation if needed
// const Settings = require('../models/settingsModel');
// const Material = require('../models/materialModel');

// --- Create a new booking ---
exports.createBooking = async (req, res, next) => { // Added next for potential error passing
    console.log('Received booking request body:', JSON.stringify(req.body, null, 2)); // Log incoming data

    const {
        selectedDate,
        timeSlotId,
        serviceAreaId,
        materialTypeId,
        estimatedWeight,
        pickupLocation,
        contactDetails // Expecting { name, phone, email }
    } = req.body;

    // --- Basic Input Validation ---
    if (!selectedDate || !timeSlotId || !serviceAreaId || !materialTypeId || !pickupLocation) {
        console.error("Validation Error: Missing required top-level fields.");
        return res.status(400).json({ success: false, message: 'Missing required booking information (date, time slot, area, material, or location).' });
    }
    if (!contactDetails || !contactDetails.name || !contactDetails.phone || !contactDetails.email) {
        console.error("Validation Error: Missing required contact details.");
        return res.status(400).json({ success: false, message: 'Missing required contact details (name, phone, or email).' });
    }

    try {
        // --- Optional: Advanced Validation (Check against current settings/materials) ---
        // This prevents booking if settings changed between frontend load and submission.
        /*
        const settings = await Settings.findOne({ singleton: 'global_settings' });
        const material = await Material.findOne({ id: materialTypeId, active: true });
        const timeSlotActive = settings?.timeSlots.find(ts => ts.id === timeSlotId)?.active;
        const serviceAreaActive = settings?.serviceAreas.find(sa => sa.id === serviceAreaId)?.active;

        if (!settings || !material || !timeSlotActive || !serviceAreaActive) {
             console.error(`Validation Error: Item inactive. Material: ${!!material}, TS Active: ${timeSlotActive}, SA Active: ${serviceAreaActive}`);
             return res.status(400).json({ success: false, message: 'Selected time slot, service area, or material is currently inactive or invalid.' });
        }
        // Add date validation logic here if needed (checking against availableDays/specialDates)
        */

        // --- Create Booking Document ---
        const newBookingData = {
            selectedDate: new Date(selectedDate), // Ensure it's a Date object
            timeSlotId,
            serviceAreaId,
            materialTypeId,
            // Store weight as number or omit if not provided/invalid
            estimatedWeight: (estimatedWeight && !isNaN(parseFloat(estimatedWeight))) ? Number(estimatedWeight) : undefined,
            pickupLocation,
            contactDetails: { // Ensure structure matches schema
                name: contactDetails.name,
                phone: contactDetails.phone,
                email: contactDetails.email
            },
            // bookingId is generated by default in the model
            // status defaults to 'confirmed'
        };

        console.log('Attempting to save booking data:', JSON.stringify(newBookingData, null, 2));

        const newBooking = new Booking(newBookingData);
        const savedBooking = await newBooking.save(); // <<< MUST AWAIT HERE

        console.log('Booking saved successfully:', savedBooking._id);

        // --- Optional: Trigger Email Confirmation ---
        // Add email sending logic here if required

        // --- Send Success Response ---
        res.status(201).json({
            success: true,
            message: 'Booking confirmed successfully!',
            // Send back the saved booking data, including the generated bookingId
            data: savedBooking
        });

    } catch (error) {
        console.error("--- Create Booking Error ---");
        console.error("Error Name:", error.name);
        console.error("Error Message:", error.message);
        if (error.name === 'ValidationError') {
            console.error("Validation Details:", JSON.stringify(error.errors, null, 2));
            // Extract a user-friendly message from validation errors
             const messages = Object.values(error.errors).map(val => val.message);
             const errorMessage = `Validation Failed: ${messages.join('. ')}`;
             return res.status(400).json({ success: false, message: errorMessage });
        }
         if (error.code === 11000) { // Duplicate key error
             console.error("Duplicate Key Details:", error.keyValue);
             return res.status(400).json({ success: false, message: `Duplicate value error: ${Object.keys(error.keyValue)[0]} already exists.` });
         }
        console.error("Full Error Stack:", error.stack); // Log full stack for debugging
        // Pass to generic error handler if not handled above
        next(error);
    }
};

// --- Optional additional controllers (add middleware as needed) ---

// Get a specific booking (e.g., for admin or user lookup)
// Add appropriate auth middleware (protectAdmin or protectClient + ownership check)
exports.getBookingById = async (req, res, next) => {
    try {
        const bookingId = req.params.id; // Can be DB _id or custom bookingId
        // Find by DB _id or custom bookingId
        const booking = await Booking.findOne({ $or: [{ _id: bookingId }, { bookingId: bookingId }] });

        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }

        // TODO: Add authorization check if needed (e.g., ensure user owns booking or is admin)

        res.status(200).json({ success: true, data: booking });
    } catch (error) {
         console.error("Get Booking Error:", error);
         // Handle potential CastError if using _id and format is wrong
         if (error.name === 'CastError' && error.kind === 'ObjectId') {
            return res.status(400).json({ success: false, message: 'Invalid booking ID format' });
         }
        next(error); // Pass to generic error handler
    }
};

// Get all bookings (Admin only)
// Add protectAdmin middleware in the route
exports.getAllBookings = async (req, res, next) => {
    try {
        // Optional: Add filtering/pagination query parameters (e.g., req.query.status, req.query.date)
        const bookings = await Booking.find(req.query) // Basic filtering via query params
                                       .sort({ selectedDate: -1, createdAt: -1 }); // Sort by pickup date, then creation date

        res.status(200).json({ success: true, count: bookings.length, data: bookings });
    } catch (error) {
        console.error("Get All Bookings Error:", error);
        next(error);
    }
};

// Update booking status (Admin only)
// Add protectAdmin middleware in the route
exports.updateBookingStatus = async (req, res, next) => {
    const { status } = req.body;
    const bookingId = req.params.id; // Can be DB _id or custom bookingId
    const allowedStatuses = ['confirmed', 'pending', 'completed', 'cancelled']; // Defined in schema enum

    if (!status || !allowedStatuses.includes(status)) {
        return res.status(400).json({ success: false, message: `Invalid status provided. Must be one of: ${allowedStatuses.join(', ')}` });
    }

    try {
        const booking = await Booking.findOneAndUpdate(
             { $or: [{ _id: bookingId }, { bookingId: bookingId }] }, // Find by DB _id or custom bookingId
            { status: status }, // Update the status field
            { new: true, runValidators: true } // Return the updated document and run schema validation
        );

        if (!booking) {
            return res.status(404).json({ success: false, message: 'Booking not found' });
        }
        res.status(200).json({ success: true, message: 'Booking status updated successfully.', data: booking });
    } catch (error) {
         console.error("Update Booking Status Error:", error);
         if (error.name === 'ValidationError') {
             const messages = Object.values(error.errors).map(val => val.message);
             return res.status(400).json({ success: false, message: `Validation Failed: ${messages.join('. ')}` });
         }
         if (error.name === 'CastError' && error.kind === 'ObjectId') {
             return res.status(400).json({ success: false, message: 'Invalid booking ID format' });
         }
        next(error);
    }
};