exports.validateRegistration = (data) => {
  console.log("--- BACKEND: utils/validators.js: validateRegistration ---");
  console.log("Data received by validator:", JSON.stringify(data, null, 2));

  const errors = {};

  const name = typeof data.name === 'string' ? data.name.trim() : '';
  const email = typeof data.email === 'string' ? data.email.trim() : '';
  const contactNumber = typeof data.contactNumber === 'string' ? data.contactNumber.trim() : '';
  const password = typeof data.password === 'string' ? data.password : '';
  const address = typeof data.address === 'string' ? data.address.trim() : '';
  const district = typeof data.district === 'string' ? data.district.trim() : '';
  const province = typeof data.province === 'string' ? data.province.trim() : '';

  if (!name) errors.name = 'Name is required.';
  else if (name.length < 3 || name.length > 50) errors.name = 'Name must be 3-50 characters.';
  else if (!/^[a-zA-Z\s]+$/.test(name)) errors.name = 'Name can only contain letters and spaces.';

  if (!email) errors.email = 'Email is required.';
  else if (!/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/.test(email)) errors.email = 'Provide a valid email.';

  if (!contactNumber) errors.contactNumber = 'Contact number is required.';
  else if (!/^[0-9]{10}$/.test(contactNumber)) errors.contactNumber = 'Provide a valid 10-digit phone number.';

  if (!password) errors.password = 'Password is required.';
  else if (password.length < 6) errors.password = 'Password: min 6 characters.';

  if (!address) errors.address = 'Address is required.';
  else if (address.length < 10) errors.address = 'Address: min 10 characters.';
  else if (address.length > 200) errors.address = 'Address: max 200 characters.';

  if (!district) errors.district = 'District is required.';
  if (!province) errors.province = 'Province is required.';

  const isValid = Object.keys(errors).length === 0;
  console.log("Errors generated by validator:", JSON.stringify(errors, null, 2));
  console.log("Is form valid (according to validator)? :", isValid);
  console.log("--- BACKEND: utils/validators.js: validateRegistration END ---");

  return {
    errors,
    isValid,
  };
};